import{getSfxForID}from"./soundGenerated.js";export const SoundSystem={};const sfxFiles=['aaaa','achievement-unlocked','baby','bejeweled','bike-bell','blackpink','blood-whistle','bubble-1','bubble-2','button','cancel-1','cancel-2','cape','cash-register-1','cash-register-2','cash-register-3','cheese-dreams','clang','coin','crazy-laugh-1','crazy-laugh-2','creepy','cuica-high','cuica-low','cursor-2','dark-soul','dithering','does-anyone-remember-this-crazy-hsr-moment','down-whistle','drill','drop-it','enter-store','erm','evil','explosion','failure-1','fire','flappy','foid','fruit','gems','germs','giwtwm','gunshot','hallelujah','halloween','holdup','init-d','item-1','jap-cymbal-1','jap-cymbal-2','jap-cymbal-3','jems','just-what-i-needed','kool','la-beast','letsa-go','lucky','male-vox-1','mammy','mario-mania','massacre','mouse-click','naruto','nega-cash-register-3','new-area','orch','pen-1','pen-2','pen-3','pen-4','pen-5','pin-it','power','pull-up-menu','put-down-menu','radio-on','ranged','rape-victim-shit','rasengan','reload','run-choose','select-1','shot','skate-or-die','spike','spotify','sssss','stab','success-1','success-2','tele-block','tele','thunder','touhou','up-whistle','wall-1','warp-whistle','wasted','why-dont-you-have-a-seat','wind-4','wolfenstein','fruit-slice','zombie','ghost-wail','skeleton-hurt','blood-water','revive','youtube','water','soda','shut-up','blood','demon','holy-magic','kurse','mini-cash-register-3','yay','glass-clink','winding-1','winding-2','winding-3','winding-4','winding-5','gold-coins','obscure-cash-register-3','diacute-cash-register-3','space-cash-register-3','dragon','rainbow','minecraft','snake-hiss','applause','diacute-cash-register-3-2','diacute-cash-register-3-3'];const radioFiles=['ARABESQUE','bioshock-infinite','club-tropicana','come-sail-away','good-people','heaven','higher','linkin-park','the-reason','unchained'];SoundSystem.sfx={};SoundSystem.soundOptions=null;SoundSystem.radio={currentSong:null,played:[],unplayed:[]};SoundSystem.radioEventQueue=[];SoundSystem.init=function(soundOptions){for(let sfxFile of sfxFiles){let sfx=new Audio(`audio/sfx/${sfxFile}.mp3`);sfx.volume=0.3;SoundSystem.sfx[sfxFile]=sfx;}
for(let radioFile of radioFiles){let song=new Audio(`audio/bgm/${radioFile}.mp3`);song.addEventListener("ended",SoundSystem.handleRadioSongEnd);SoundSystem.radio.unplayed.push(song);}
SoundSystem.soundOptions=soundOptions;SoundSystem.shuffleRadio();SoundSystem.wind=new Audio("audio/wind.mp3");SoundSystem.wind.volume=0.75
SoundSystem.wind.loop=true;SoundSystem.wind.autoplay=soundOptions.enableAmbience;startupOppaW3CNiggerStyle(()=>{if(SoundSystem.soundOptions.enableAmbience){SoundSystem.playAmbience();}
if(SoundSystem.soundOptions.enableRadio){SoundSystem.radioEventQueue.push(setTimeout(SoundSystem.playRadioSong,Math.random()*16000+4000));}});}
function startupOppaW3CNiggerStyle(fn){function handler(){document.removeEventListener("click",handler);document.removeEventListener("touchstart",handler);document.removeEventListener("pointerdown",handler);fn();}
document.addEventListener("click",handler,{once:true});document.addEventListener("touchstart",handler,{once:true});document.addEventListener("pointerdown",handler,{once:true});}
SoundSystem.clearRadioEventQueue=function(){while(SoundSystem.radioEventQueue.length>0){clearInterval(SoundSystem.radioEventQueue.pop());}}
SoundSystem.startRadio=function(callback){SoundSystem.clearRadioEventQueue();4
if(callback){SoundSystem.radioEventQueue.push(setTimeout(callback,5000));}
SoundSystem.sfx["radio-on"].addEventListener("ended",()=>{SoundSystem.radioEventQueue.push(setTimeout(SoundSystem.playRadioSong,Math.random()*2000+1000));},{once:true});SoundSystem.playSfx(SoundSystem.sfx["radio-on"]);}
SoundSystem.shuffleRadio=function(){SoundSystem.radio.unplayed.sort((a,b)=>{return Math.random()-0.5;});if(SoundSystem.radio.currentSong){let spot=Math.floor(Math.random()*(SoundSystem.radio.unplayed.length-1));SoundSystem.radio.unplayed.splice(spot,0,SoundSystem.radio.currentSong);SoundSystem.radio.currentSong=null;}}
SoundSystem.playRadioSong=function(){if(SoundSystem.radioEventQueue.length>0){SoundSystem.clearRadioEventQueue();}
if(!SoundSystem.soundOptions.enableRadio){SoundSystem.stopRadio();return;}
SoundSystem.radio.currentSong=SoundSystem.radio.unplayed.shift();SoundSystem.radio.currentSong.volume=SoundSystem.soundOptions.radioVolume>=0&&SoundSystem.soundOptions.radioVolume<=1.0?(Math.pow(SoundSystem.soundOptions.radioVolume,2.5))*0.5:0.24683332*0.5;SoundSystem.radio.currentSong.pause();SoundSystem.radio.currentSong.currentTime=0;SoundSystem.radio.currentSong.play();}
SoundSystem.stopRadio=function(){if(SoundSystem.radio.currentSong){SoundSystem.radio.currentSong.pause();}
if(SoundSystem.sfx["radio-on"].currentTime>0){SoundSystem.sfx["radio-on"].pause();SoundSystem.sfx["radio-on"].currentTime=0;}
SoundSystem.clearRadioEventQueue();for(let i=0;i<SoundSystem.radio.played.length;i++){SoundSystem.radio.unplayed.push(SoundSystem.radio.played.pop());}
SoundSystem.shuffleRadio();}
SoundSystem.updateRadioVolume=function(){if(SoundSystem.radio.currentSong){SoundSystem.radio.currentSong.volume=SoundSystem.soundOptions.radioVolume>=0&&SoundSystem.soundOptions.radioVolume<=1.0?(Math.pow(SoundSystem.soundOptions.radioVolume,2.5)):0.24683332;}}
SoundSystem.handleRadioSongEnd=function(){if(SoundSystem.radio.unplayed.length==0){SoundSystem.stopRadio();SoundSystem.radioEventQueue.push(setTimeout(SoundSystem.playRadioSong,Math.random()*13000+2000));return;}
SoundSystem.radio.played.push(SoundSystem.radio.currentSong);SoundSystem.radioEventQueue.push(setTimeout(SoundSystem.playRadioSong,Math.random()*13000+2000));}
SoundSystem.playAmbience=function(){SoundSystem.wind.play();}
SoundSystem.stopAmbience=function(){SoundSystem.wind.pause();}
SoundSystem.playSfx=function(sfx,volume=1.0){if(SoundSystem.soundOptions.enableSfx){sfx.pause();sfx.volume=volume;sfx.currentTime=0;sfx.play();}}
SoundSystem.stopSfx=function(sfx){sfx.pause();}
SoundSystem.playSelectSfx=function(id,classes){let selectSfx=getSfxForID(id,classes);SoundSystem.playSfx(SoundSystem.sfx[selectSfx]);}
SoundSystem.stopSelectSfx=function(id,classes){let selectSfx=getSfxForID(id,classes);SoundSystem.stopSfx(SoundSystem.sfx[selectSfx]);}